### ISSUE TITLE
Example code doesn't run on Windows?

### ISSUE THREAD

**Issue by joshpeng** [scottworkman/deephorizon#2]
When I run ```python example.py``` on Windows 10 with Python 2.7 I hit this. Any ideas? Thanks.
```
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    center_im, crop_info = center_crop(im)
  File "example.py", line 22, in center_crop
    c_im = im[y_inds[0]:y_inds[1]+1, x_inds[0]:x_inds[1]+1, :]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by jacobsn** [comment]
Does the problem go away if you cast `y_inds` and `x_inds` to integers?

**Comment by joshpeng** [comment]
Just tried, yes it does. Thanks.

**Comment by jacobsn** [comment]
Thanks!  Glad the workaround worked.

We probably can't get to this in the next few weeks but will try to implement a more satisfactory solution when we have some spare cycles.

**Comment by bluizh** [comment]
@joshpeng hi，I am using the command "./ download_model.sh "to find that I can't download it. How did you use it?
