### ISSUE TITLE
./download_models.sh --demo is error

### ISSUE THREAD

**Issue by bluizh** [scottworkman/deephorizon#3]
I can‘t link the URL='http://amos.csr.uky.edu/modelzoo/deephorizon/deephorizon_single.zip', and it refuse
 me.

**Comment by jacobsn** [comment]
We have been having some server issues lately.  I will look into it.  In the meantime, you can download from Google Drive: https://drive.google.com/file/d/14pkbQRKrCdw1t8m7cOZ99EkXJ-kM7e4V/view?usp=sharing.

**Comment by bluizh** [comment]
The demo has been successfully run. Thanks.

**Comment by jacobsn** [comment]
Great.  It turns out our web server had been shut down while we were debugging some file system lag.
